### ISSUE TITLE
How to specify journal abbreviation

### ISSUE THREAD

**Issue by Klortho** [Klortho/eutils-org#20]
See [this thread](https://groups.google.com/forum/#!topic/jats2rdf/eNOVjjWRicY).

What we have now (see [this graph](https://f.cloud.github.com/assets/77226/2023676/10bffc84-885f-11e3-9fa9-3f29a5289b47.png)):

```
<rdf:Description rdf:nodeID="journal">
    <datacite:hasIdentifier>
        <rdf:Description>
            <rdf:type rdf:resource="http://purl.org/spar/datacite/Identifier"/>
            <datacite:usesIdentifierScheme rdf:resource="http://purl.org/spar/datacite/local-resource-identifier-scheme"/>
            <literal:hasLiteralValue>Balisage Ser Markup Technol</literal:hasLiteralValue>
            <prov:wasAttributedTo>
                <rdf:Description>
                    <rdf:type rdf:resource="http://www.w3.org/ns/prov#Agent"/>
                    <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Organization"/>
                    <rdfs:label>PubMed</rdfs:label>
                </rdf:Description>
            </prov:wasAttributedTo>
        </rdf:Description>
    </datacite:hasIdentifier>
</rdf:Description>
```

**Comment by Klortho** [comment]
Referring to this snippet from the original XML:

``` xml
    <journal-meta>
      <journal-id journal-id-type="nlm-journal-id">101566482</journal-id>
      <journal-id journal-id-type="pubmed-jr-id">39470</journal-id>
      <journal-id journal-id-type="nlm-ta">Balisage Ser Markup Technol</journal-id>
      <journal-title-group>
        <journal-title>Balisage series on markup technologies</journal-title>
      </journal-title-group>
      <issn pub-type="epub">1947-2609</issn>
    </journal-meta>
```

Silvio will create two new properties in fabio:  one for the "nlm-journal-id", which is a numerical identifiers, and one for "nlm-ta" (title abbreviation).  These are both identifiers, and so, could perhaps both be subproperties of fabio:hasNationalLibraryOfMedicineJournalId, although personally I think maybe that is overkill.  I would rather see fabio:hasNationalLibraryOfMedicineJournalId more tightly constrained so that it is always used for the numerical ID, and create one more property for the title abbr.

**Comment by essepuntato** [comment]
Deal all,

day 17/feb/2014, 23:51, Chris Maloney notifications@github.com wrote:

> Referring to this snippet from the original XML:
> 
> ```
> <journal-meta>
>   <journal-id journal-id-type="nlm-journal-id">101566482</journal-id>
>   <journal-id journal-id-type="pubmed-jr-id">39470</journal-id>
>   <journal-id journal-id-type="nlm-ta">Balisage Ser Markup Technol</journal-id>
>   <journal-title-group>
>     <journal-title>Balisage series on markup technologies</journal-title>
>   </journal-title-group>
>   <issn pub-type="epub">1947-2609</issn>
> </journal-meta>
> ```
> 
> Silvio will create two new properties in fabio: one for the "nlm-journal-id", which is a numerical identifiers, and one for "nlm-ta" (title abbreviation). These are both identifiers, and so, could perhaps both be subproperties of fabio:hasNationalLibraryOfMedicineJournalId, although personally I think maybe that is overkill. I would rather see fabio:hasNationalLibraryOfMedicineJournalId more tightly constrained so that it is always used for the numerical ID, and create one more property for the title abbr.
> 
> I see. Well, another choice could be to specify that “fabio:hasNationalLibraryOfMedicineJournalId” must have a numeric value, while we can create a new “fabio:hasNationalLibraryOfMedicineJournalTitleAbbreviation” which is a subproperty of both dcterms:identifier and fabio:hasShortTitle.

What do you think?

Have a nice day :-)

S.

**Comment by essepuntato** [comment]
Hi all,

this sounds good to me,

cheers,

**Comment by essepuntato** [comment]
Hi All,

Sounds good to me as well!

Best,
Gang

**Comment by Klortho** [comment]
I changed this as discussed.
