### ISSUE TITLE
Please add new fabio property

### ISSUE THREAD

**Issue by Klortho** [Klortho/eutils-org#29]
As we discussed on #20, @essepuntato , could you add a new property to fabio?  I am using "fabio:hasNlmJournalTitleAbbr", rather than "fabio:hasNationalLibraryOfMedicineJournalTitleAbbreviation", because the latter just seems ridiculously long.  I hope that's okay.

And, please change the http://purl.org/spar/fabio/hasNationalLibraryOfMedicineJournalId into a datatype property that takes a numeric value.

**Comment by essepuntato** [comment]
Dear Chris, all,

> As we discussed on #20, @essepuntato , could you add a new property to fabio? I am using "fabio:hasNlmJournalTitleAbbr", rather than "fabio:hasNationalLibraryOfMedicineJournalTitleAbbreviation", because the latter just seems ridiculously long. I hope that's okay.
> 
> I’ve just changed the range of fabio:hasNationalLibraryOfMedicineJournalId in order to specify only numeric strings, and I’ve added fabio:hasNLMJournalTitleAbbreviation having as range a string. Let me know if it makes sense to have a fabio:Journal (i.e., an FRBR Expression) as domain, or if it is better to leave the current one (i.e., frbr:Endeavour).

@Chris: sorry not to follow your suggestion there, but we would like to follow the guidelines we used for the development of all the SPAR ontologies, which impose not to use abbreviation in entities URL, while acronyms for well-known entities, such as the National Library of Medicine, are permitted. That’s why I used “NLM”  and “JournalTitleAbbreviation” in the new property. I hope it is fine.

Have a nice day :-)

S.

**Comment by Klortho** [comment]
Not a problem.  Thanks for adding it -- I will change my code to reflect the new name.
